spring.application.name=billing-processor

spring.kafka.bootstrap-servers=localhost:9092
app.kafka.telemetry-topic=car-telemetry

# ===============================
# Configuracoes do Banco de Dados (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_db
spring.datasource.username=billing_user
spring.datasource.password=billing_password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Configuracoes do JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Use 'update' em dev para criar as tabelas automaticamente. Em prod, mude para 'validate'.
spring.jpa.hibernate.ddl-auto=update

# Exibe no console as queries SQL que o Hibernate esta rodando
spring.jpa.show-sql=true